//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTA_HighSchools_DataTier
{
    using System;
    using System.Collections.Generic;
    
    public partial class GradeSubjectTeacher
    {
        public int SubjectID { get; set; }
        public int TeacherID { get; set; }
        public Nullable<int> GradeID { get; set; }
    
        public virtual Grade Grade { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
