//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTA_HighSchools_DataTier
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Session()
        {
            this.Students = new HashSet<Student>();
            this.Teachers = new HashSet<Teacher>();
        }
    
        public int SessionID { get; set; }
        public Nullable<int> VenueID { get; set; }
        public Nullable<int> WeekdayID { get; set; }
        public int SessionTypeID { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public int AcademicYearID { get; set; }
    
        public virtual AcademicYear AcademicYear { get; set; }
        public virtual SessionType SessionType { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual Venue Venue { get; set; }
        public virtual Weekday Weekday { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student> Students { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Teacher> Teachers { get; set; }
    }
}
